version: '3.2'

services:

  selenium:
    container_name: selenium-chrome
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: "2gb"

  python:
    # イメージ名を指定
    image: atcoder_offline:1.0

    build:
      context: .
      dockerfile: Dockerfile

    container_name: atcoder_offline
    stdin_open: true
    tty: true
    working_dir: '/work'
    volumes:
      - ../:/work
